blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = "blog"

urlpatterns = [
    path('', render_posts, name="posts"),
    path('<int:post_id>', post_detail, name="post_detail")
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('blog/', include("blog.urls"))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path


urlpatterns = [
    
]

blog/models.py
from django.db import models
import datetime
import os

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    imgs = models.ImageField(upload_to='blog/post_images')
    date = models.DateField(datetime.date.today)
    
class PostImage(models.Model):
    def post_image_upload_to(instance, filename):
        # Genera la ruta basada en el título del post
        post_title = instance.post.title.replace(" ", "_")  # Reemplaza espacios por guiones bajos
        return os.path.join(f'blog/images/post_images/{post_title}', filename)
    
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=post_image_upload_to)
    caption = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return f"Image for {self.post.title}"

certificates/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
import datetime
# Create your models here.

class Technology(models.Model):
    CATEGORY_CHOICES = [
        ('language', 'Lenguaje'),
        ('framework', 'Framework'),
        ('software', 'Software'),
        ('tool', 'Herramienta'),
        ('library', 'Librería'),
        ('other', 'Otro'),
    ]
    
    name = models.CharField(max_length=100, unique=True)
    icon = models.ImageField(upload_to='portfolio/images/technologies',blank=True, null=True)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    
    def __str__(self):
        return self.name
    
class Certificate(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    technologies = models.ManyToManyField(Technology, related_name="all_technologies")
    image = models.ImageField(upload_to='portfolio/images/certificates')
    date = models.DateField(default=datetime.date.today)
    url = URLField(blank=True)
    
    def __str__(self):
        return self.name

portfolio/models.py
from django.db import models
from certificates.models import Technology

from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField

# Create your models here.

class Projects(models.Model):
    title = CharField(max_length=100)
    description = models.TextField()
    technologies = models.ManyToManyField(Technology, related_name="all_technologies_projects")
    image = ImageField(upload_to='portfolio/images/projects')
    url = URLField(blank=True)
    isPortfolio = models.BooleanField(default=False)

workexpirence/models.py
from django.db import models
from certificates.models import Technology

from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField

# Create your models here.

class WorkExpirence(models.Model):
    title = CharField(max_length=100)
    description = models.TextField()
    technologies = models.ManyToManyField(Technology, related_name="all_technologies_workexpirence")
    image = ImageField(upload_to='portfolio/images/workexpirence')
    location = URLField(blank=True)
    initial_date = models.DateField(blank=True, null=True)
    final_date = models.DateField(blank=True, null=True)

blog/views.py
from django.shortcuts import get_object_or_404, render
from .models import Post
# Create your views here.

def render_posts(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'post.html',{
        'posts': posts
    })

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {
        "post": post
    })

portfolio/views.py
from django.shortcuts import render, get_object_or_404
from .models import Projects
from certificates.models import Certificate
from workexpirence.models import WorkExpirence

# Create your views here.
def home(request):
    projects = Projects.objects.all()
    certificates = Certificate.objects.all().order_by('date')
    workexpirence = WorkExpirence.objects.all()
    
    return render(request, 'home.html',{
        'projects' : projects,
        'certificates' : certificates,
        'workexpirence' : workexpirence
    })
    

workexpirence/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/post.html
{% extends "layout.html" %} {% block content %}
<div class="container p-4 my-4 text-center fst-italic">
  <div class="row my-4 text-center cards-row">
    <h1>Posts</h1>
    {% for post in posts %}
    <div class="col-md-4 p-4 mx-4 my-4 card-container">
      <div class="card-inner">
        <h3>{{post.date|date:'M d Y'|upper}}</h3>
        <div class="card-front card">
          <h2>{{post.title}}</h2>
          <img src="{{post.imgs.url}}" alt="{{post.title}}" class=""/>
          <p>{{post.description|striptags|truncatechars:100}}</p>
          <a href="{% url 'blog:post_detail' post.id %}" 
          class="btn btn-light btn-sm fw-bold fst-italic">
          {{post.title}}</a>
        </div>   
      </div>
    </div>
  {% endfor %}
  </div>
</div>
{% endblock %}

blog/templates/post_detail.html
{% extends "layout.html" %} {% block content %}

<div class="container  my-4 text-center fst-italic">
  <div class="row my-4 text-center cards-row">
  <h3>{{post.date|date:'F jS Y'}}</h3> 
    <div class="row my-4 text-center cards-row">
      <h2>{{post.title}}</h2>
      <div class="col-md-8 ">
        <div class="card-inner">
          <div class="card-front card">
              <img src="{{post.imgs.url}}" alt="{{post.title}}" class="img-fluid"/>   
          </div>
        </div>
      <h3>{{post.description|safe}}</h3>
      </div>
    </div>

    {% for image in post.images.all %}
    <div class="container  my-4 text-center fst-italic">
      <div class="row my-4 text-center cards-row">
        <div class="col-md-8 ">
          <div class="card-inner">
            <div class="card-front card">
              <img src="{{ image.image.url }}" alt="{{ post.title }}" class="img-fluid"/>    
            </div>
          </div>
          <h3>{{ image.caption }}</h3>
        </div>
      </div>
    </div>
  {% endfor %}
  </div>
</div>
{% endblock %}

portfolio/templates/home.html
{% extends "layout.html" %} {% block content %} {% load static %}

<div class="intro fst-italic">
  <img src="{% static 'portfolio/img/ChibyJNoBorders.png' %}" alt="Intro Image"/>
  <h1 class="logo">
    <span class="logo-parts">J</span>
    <span class="logo-parts">o</span>
    <span class="logo-parts">h</span>
    <span class="logo-parts">a</span>
    <span class="logo-parts">n</span>
    <span class="logo-parts"> </span>
    <span class="logo-parts">A</span>
    <span class="logo-parts">l</span>
    <span class="logo-parts">f</span>
    <span class="logo-parts">a</span>
    <span class="logo-parts">r</span>
    <span class="logo-parts">o</span>
  </h1>

  <h2>FullStack Developer</h2>
  <h2>Portfolio...</h2>
</div>
<div class="container  fst-italic">
  <header class="row">
    <div class="col-md-3">
      <center>
        <img src="{% static 'portfolio/img/JohanHarman.jpeg' %}" alt="Profile Image" class="img-fluid rounded-circle me"/>
      </center>
    </div>
    <div class="col-md-9">
        <h1>Hello my name is</h1>
        <h1><strong>Johan Alejandro Ontiveros Alfaro</strong></h1>
        <h3>I see myself as a future FullStack developer, and I am focused on learning to apply django in the backend and the use of React in frontend.</h3>
        <h3><strong>Some of my technical skills:</strong></h3>  
      <div class="row">
        <div class="col-md-9">
          <ul class="skills">
            <li>Lenguajes: "Spanish: native" and "English: B1".</li>
            <li>Programming languages: JavaScript, Python and PHP</li>
            <li>Frameworks: Django and Symfony</li>
            <li>Libraries: React, JQuery, ChartJS</li>
            <li>DataBases: MySQL, MariaDB, firebase and SQLServer</li>
            <li>Im learning: Django, React (Vite), Astro, PostgreSQL and SQLServer</li>
          </ul>
        </div>  
        <div class="col-md-3">   
            <center>
            <a
            href="{% static 'portfolio/Spanish_CV_OntiverosAlfaroJohanAlejandro.pdf' %}"
            class="btn btn-light  btn-sm fw-bold fst-italic" target="_blank">Download Spanish CV</a>
              <a
            href="{% static 'portfolio/English_CV_OntiverosAlfaroJohanAlejandro.pdf' %}"
            class="btn btn-light  btn-sm fw-bold fst-italic" target="_blank">Download English CV</a>
          </center>
        </div>
      </div>
  </div>
    
  </header>
</div>

<div class="container  my-4 text-center fst-italic">
  <div class="row my-4 text-center cards-row">
    <h3>Work experience</h3>
    {% for experience in workexpirence %}
    <div class="col-md-4 ">
      <div class="flip-card">
        <h3>{{ experience.initial_date }} – {% if experience.final_date %}{{ experience.final_date }}{% else %}Current{% endif %}</h3>
            
        <div class="card-inner">
          <!-- Frente -->
          <div class="card-front card">
            <h2>{{ experience.title }}</h2>
            <img src="{{ experience.image.url }}" alt="{{ experience.title }}" class="card-img-fluid"/>
            <p>{{ experience.description }}</p>
          </div>
          <!-- Reverso -->
          <div class="card-back card">
            <h2>Technologies</h2>
            <ul>
              {% for tech in experience.technologies.all %}
              <li>
                <img src="{{ tech.icon.url }}" alt="{{ tech.name }}" class="tech-icon"/>
                <span>{{ tech.name }}</span>
              </li>
              {% endfor %}
            </ul>
            {% if experience.location %}
              <a href="{{ experience.location }}" class="btn btn-light  btn-sm fw-bold fst-italic" target="_blank">Look at this project</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<div class="container  my-4 text-center fst-italic">
  <div class="row my-4 cards-row">
    <h3>Some Projects made by me</h3>
    {% for project in projects %}
      {% if project.isPortfolio == False %}
        <div class="col-md-4 ">
          <div class="flip-card">
            <div class="card-inner">
              <!-- Frente -->
              <div class="card-front card">
                <h2>{{ project.title }}</h2>
                <img src="{{ project.image.url }}"
                    alt="{{ project.title }}"
                    class="card-img-fluid img-fluid"/>
                <p>{{ project.description }}</p>
              </div>
              <!-- Reverso -->
              <div class="card-back card">
                <h2>Technologies</h2>
                <ul class="list-inline">
                  {% for tech in project.technologies.all %}
                    <li class="list-inline-item">
                      <img src="{{ tech.icon.url }}"
                          alt="{{ tech.name }}"
                          class="tech-icon"/>
                      <span>{{ tech.name }}</span>
                    </li>
                  {% endfor %}
                </ul>
                {% if project.url %}
                  <a href="{{ project.url }}"
                    class="btn btn-light  btn-sm fw-bold fst-italic"
                    target="_blank">Look at this project</a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </div>
</div>

<div class="container  my-4 text-center fst-italic">
  <div class="row my-4 cards-row">
    <h3>Customized/designed portfolios by me</h3>
    {% for project in projects %}
      {% if project.isPortfolio == True %}
      <div class="col-md-4 ">
          <div class="flip-card">
            <div class="card-inner">
              <!-- Frente -->
              <div class="card-front card">
                <h2>{{ project.title }}</h2>
                <img src="{{ project.image.url }}"
                    alt="{{ project.title }}"
                    class="card-img-fluid img-fluid"/>
              </div>
              <!-- Reverso -->
              <div class="card-back card">
                <p>{{ project.description }}</p>
                <h2>Technologies</h2>
                <ul class="list-inline">
                  {% for tech in project.technologies.all %}
                    <li class="list-inline-item">
                      <img src="{{ tech.icon.url }}"
                          alt="{{ tech.name }}"
                          class="tech-icon"/>
                      <span>{{ tech.name }}</span>
                    </li>
                  {% endfor %}
                </ul>
                {% if project.url %}
                  <a href="{{ project.url }}"
                    class="btn btn-light  btn-sm fw-bold fst-italic"
                    target="_blank">Look at this project</a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </div>
</div>

<div class="container  my-4 text-center fst-italic">
  <div class="row my-4 cards-row">
    <h3>My courses and certificates</h3>
    {% for cert in certificates %}
      <div class="col-md-4 ">
        <div class="flip-card">
          <h3>{{ cert.date }}</h3>
          <div class="card-inner">
            <!-- Frente -->
            <div class="card-front card">
              <h2>{{ cert.name }}</h2>
              <img src="{{ cert.image.url }}"
                   alt="{{ cert.name }}"
                   class="card-img-fluid img-fluid"
                   width="400"/>
            </div>
            <!-- Reverso -->
            <div class="card-back card">
              <p>{{ cert.description }}</p>
              <h2>Technologies</h2>
              <ul class="list-inline">
                {% for tech in cert.technologies.all %}
                  <li class="list-inline-item">
                    <img src="{{ tech.icon.url }}"
                         alt="{{ tech.name }}"
                         class="tech-icon"
                         width="40" height="40"/>
                    <span>{{ tech.name }}</span>
                  </li>
                {% endfor %}
                

              </ul>
              
              {% if cert.url %}
                <a href="{{ cert.url }}"
                   class="btn btn-light btn-sm fw-bold fst-italic"
                   target="_blank">Look at this course</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
<br>
{% endblock %}

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'portfolio/css/main.css' %}">
    <title>Django Portfolio</title>
</head>

<body>

    {% include 'partials/navbar.html' %}

    
    {% block content %}
    {% endblock %}

    {% include 'partials/footer.html' %}
    <script src="{% static 'portfolio/js/intro.js' %}"></script>
</body>

</html>

portfolio/templates/partials/footer.html
{% load static %}

<footer>
    <div class="container text-center fst-italic">
        <h2>Follow or contact me</h2>
        <br>
        <div class="social-icons">
            <div class="social-item">
                <a href="https://github.com/ChemsJam" target="_blank">
                    <img src="{% static 'portfolio/icons/icons8-github-50.png' %}" alt="GitHub" width="40" height="40">
                </a>
                <span>        
                    GitHub
                </span>
            </div>
            <div class="social-item">
                <a href="https://www.linkedin.com/in/johan-alejandro-ontiveros-alfaro-5990a5287" target="_blank">
                    <img src="{% static 'portfolio/icons/icons8-linkedin-50.png' %}" alt="LinkedIn" width="40" height="40">
                </a>
                <span>        
                    LinkedIn
                </span>
            </div>
            <div class="social-item">
                <a href="https://www.facebook.com/johan.alfaro.320200/" target="_blank">
                    <img src="{% static 'portfolio/icons/icons8-facebook-50.png' %}" alt="Facebook" width="40" height="40">    
                </a>
                <span>        
                    Facebook
                </span>
            </div>
            <div class="social-item">
                <a href="https://www.instagram.com/johanalfaro2111/" target="_blank">
                    <img src="{% static 'portfolio/icons/icons8-instagram-50.png' %}" alt="Instagram" width="40" height="40">
                </a>
                <span>        
                    Instagram
                </span>
            </div>
            <div class="social-item">
                <a href="https://x.com/AlexJrDev21" target="_blank">
                    <img src="{% static 'portfolio/icons/icons8-x-50.png' %}" alt="X" width="40" height="40">
                </a>
                <span>
                    X
                </span>
            </div>
            <div class="social-item">
                <a href="https://www.youtube.com/@AlexDev21" target="_blank">
                    <img src="{% static 'portfolio/icons/icons8-youtube-50.png' %}" alt="YouTube" width="40" height="40">
                </a>
                <span>
                    YouTube 
                </span>
            </div>
            <div class="social-item">
                <a href="https://www.tiktok.com/@alexjrdev21" target="_blank">
                    <img src="{% static 'portfolio/icons/icons8-tiktok-50.png' %}" alt="TikTok" width="40" height="40">
                </a>
                <span>
                    TikTok
                </span>
            </div>
            
            <div class="social-item">
                <a href="https://wa.me/5214445887659" target="_blank">
                    <img src="{% static 'portfolio/icons/icons8-whatsapp-50.png' %}" alt="WhatsApp" width="40" height="40">
                </a>
                <span>        
                    WhatsApp
                </span> 
            </div>
            <div class="social-item">
                <a href="https://mail.google.com/mail/?view=cm&fs=1&to=johalfaro1174@gmail.com&su=Contact%20from%20Portfolio&body=Hello%20Johan,%0A%0AI%20would%20like%20to%20get%20in%20touch%20with%20you." target="_blank">
                    <img src="{% static 'portfolio/icons/icons8-gmail-50.png' %}" alt="Gmail" width="40" height="40">
                </a>
                <span>
                    Gmail
                </span>
            </div>
            <div class="social-item">
                <a href="#" onclick="alert('Add me on Discord: Jomhám Fider#3213 ID: 755472058560806932'); return false;">
                    <img src="{% static 'portfolio/icons/icons8-discord-50.png' %}" alt="Discord" width="40" height="40">
                </a>
                <span>
                    Discord
                </span>
            </div>
        </div>
    </div>
</footer>

portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg">
  <div class="container">
    <a class="btn btn-light  btn-sm fw-bold fst-italic" href="/">Projects portfolio</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarText"
      aria-controls="navbarText"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item p-3">
          <a
            class="btn btn-light  btn-sm fw-bold fst-italic"
            aria-current="page"
            href="{% url 'blog:posts' %}"
            >Blog</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<br>